### ISSUE TITLE
Send/Recive all images at once?

### ISSUE THREAD

**Issue by annk15** [annk15/MTGKeywordHelper#33]
Now when we know that the frontend has a way to handle images as blobs. We could create an endpoint which returns a large JSON file with all images, artists and keywords. 
The benefit of this is that it will be faster for the client to receive a big image bundle in comparison to single image at a time. This is due to how networking works as there is a overhead each time a file is sent/received (That's one reason you usually compress files, which we also could look in to the future). The backend could even prepare this bundle so it is cached to optimise it even further.

It will require changes to both frontend and backend so I think we should have a discussion if this is something we want to do.

**Comment by annk15** [comment]
It seems like we can encode the images as base64 then load them using this in JavaScript imgElement.src = `data:image/jpeg;base64,${base64Image}`;
Then we don't have to use blobs 👍

**Comment by OscarLarm** [comment]
> It seems like we can encode the images as base64 then load them using this in JavaScript imgElement.src = `data:image/jpeg;base64,${base64Image}`; Then we don't have to use blobs 👍

Neat!

**Comment by annk15** [comment]
Never mind, the oracle suggests the second option (our current implantation) so we should most likely keep this as it is.

When dealing with over 100 images, performance efficiency becomes crucial. Here's an analysis of the two methods:

### 1. **Base64 Encoding in JSON**
**Advantages:**
- **Single Request**: All data is fetched in a single request.
- **Self-contained Data**: No need for additional requests to fetch images.

**Disadvantages:**
- **Larger Payload**: Base64 encoding increases the size of the data by about 33%. This can lead to significantly larger JSON responses, increasing bandwidth usage and load times.
- **Memory Usage**: The client needs to decode the Base64 strings, which can be memory-intensive, especially with many large images.
- **Initial Load Time**: All images are downloaded before the user can see any of them, leading to slower initial page load.

### 2. **Sending Metadata and Fetching Images Separately**
**Advantages:**
- **Smaller Initial Payload**: The initial JSON response is small, containing only metadata (e.g., URLs).
- **Incremental Loading**: Images can be loaded incrementally, allowing the page to become interactive more quickly.
- **Browser Optimization**: Browsers are optimized for loading and caching images, which can lead to more efficient resource handling.

**Disadvantages:**
- **Multiple Requests**: Requires multiple HTTP requests, which can lead to overhead. However, modern browsers handle concurrent requests efficiently, and HTTP/2 can mitigate much of this overhead by multiplexing requests over a single connection.
- **Dependency on Network Conditions**: The loading experience can vary based on network conditions and latency.

### Conclusion
**For performance efficiency, especially with a large number of images, the second method (sending metadata and fetching images separately) is generally better.**

### Implementation of the Recommended Method
Here’s how you can implement the method of sending metadata and fetching images separately:

#### Flask Server

```python
from flask import Flask, jsonify, send_from_directory
import os

app = Flask(__name__)

IMAGE_FOLDER = 'static/images'

@app.route('/images', methods=['GET'])
def list_images():
    images = os.listdir(IMAGE_FOLDER)
    image_urls = [f'/image/{image}' for image in images]
    return jsonify({'images': image_urls})

@app.route('/image/<filename>', methods=['GET'])
def get_image(filename):
    return send_from_directory(IMAGE_FOLDER, filename)

if __name__ == '__main__':
    app.run(debug=True, port=3000)
```

#### Client-Side: HTML/JavaScript

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Display Multiple Images from JSON</title>
</head>
<body>

<div id="imageContainer"></div>

<script>
fetch('/images')
  .then(response => response.json())
  .then(data => {
    const imageContainer = document.getElementById('imageContainer');
    
    data.images.forEach(imageUrl => {
      const imgElement = document.createElement('img');
      imgElement.src = imageUrl;
      imgElement.alt = 'Loaded from Flask';
      imageContainer.appendChild(imgElement);
    });
  })
  .catch(error => {
    console.error('Error:', error);
  });
</script>

</body>
</html>
```

### Explanation:

1. **Flask Server**:
    - **/images Endpoint**: Lists image URLs in a JSON response.
    - **/image/<filename> Endpoint**: Serves individual image files from the specified directory.

2. **Client-Side**:
    - Fetches the JSON response containing image URLs.
    - Iterates through the image URLs and creates `img` elements for each one.
    - Appends the `img` elements to a container in the DOM, allowing the browser to handle the loading and caching of images.

### Additional Optimizations
To further improve performance, consider the following optimizations:

- **Lazy Loading**: Use the `loading="lazy"` attribute on `img` elements to defer loading off-screen images until the user scrolls near them.
- **Caching**: Ensure proper caching headers are set on the server to allow the browser to cache images.
- **Image Optimization**: Compress images to reduce file size without significantly reducing quality.
- **HTTP/2**: Ensure your server supports HTTP/2 to take advantage of multiplexed connections for multiple image requests.

By using the method of sending metadata and fetching images separately, combined with these optimizations, you can achieve better performance and a smoother user experience.

**Comment by annk15** [comment]
The frontend should most likely use lazy loading and I should send the caching headers and compress the images before I store them in the database to improve the performance

**Comment by OscarLarm** [comment]
> The frontend should most likely use lazy loading and I should send the caching headers and compress the images before I store them in the database to improve the performance

If that is the machine spirits will 🤓 

<img src = 'https://media1.tenor.com/m/zw3HWomJs3YAAAAd/darktide-adeptus-mechanicus.gif'>

**Comment by OscarLarm** [comment]
> The frontend should most likely use lazy loading and I should send the caching headers and compress the images before I store them in the database to improve the performance

It looks like loading="lazy" is only available as a attribute for img elements. I'm currently working on a card design branch and I think we need the images to be backgroundimages, for it to look good and scale properly. 

Lazy loading doesn't seem to be available to backgroundimages from what I can gather.

**Comment by annk15** [comment]
> > The frontend should most likely use lazy loading and I should send the caching headers and compress the images before I store them in the database to improve the performance
> 
> 
> 
> It looks like loading="lazy" is only available as a attribute for img elements. I'm currently working on a card design branch and I think we need the images to be backgroundimages, for it to look good and scale properly. 
> 
> 
> 
> Lazy loading doesn't seem to be available to backgroundimages from what I can gather.

Ah ok, then we skip it for now.
I will look in to the caching mechanisms as I think those will have the biggest impact on performance
