### ISSUE TITLE
Problem with MIME type after folder restructure

### ISSUE THREAD

**Issue by OscarLarm** [annk15/MTGKeywordHelper#42]
The new development branch seems to have some issues with the server.  The CSS and JS files are being loaded with the MIME type text/html, which is causing them to not be loaded.

**Comment by annk15** [comment]
So the CSS won't load at all?

**Comment by annk15** [comment]
I will have a look at this later and see if I can replicate the issue 🃏

**Comment by OscarLarm** [comment]
Yeah neither css or javascript

**Comment by annk15** [comment]
I have now tested this and it works for me after I changed the database address to 127.0.0.1 in the config.js . Does this work for you?

**Comment by annk15** [comment]
Are you running the script or using live server? 🤔 You have to use the script to host the required routes.
