### ISSUE TITLE
How should we do with the .env?

### ISSUE THREAD

**Issue by annk15** [annk15/MTGKeywordHelper#59]
I have looked in to the best practices for the .env and as mentioned before we should change the name of this file to prevent accidents in the future. The most common way is just remove this file and create a .env.example and fill it with template data (In our case the same content as we have in the .env today). I don't like this method as I think it makes it harder for new users to deploy the project. My first thought of adding a "template" .env file and then add it to the ignore file will not work according to [this](https://stackoverflow.com/a/63026268):

(Adding a file Git is already tracking to .gitignore has no effect.

A gitignore file specifies intentionally untracked files that Git should ignore. Files already tracked by Git are not affected)

I would prefer something like [this](https://stackoverflow.com/a/54896866), the problem is that some users may go against this not knowing that secrets should be kept in the .env.local and still add the variables to the .env and we have the same problem as if we commit the .env

In the end I think the best way would be to commit an .env.example as the best practice suggests to help developers list the variables used. 

Then we have two options create an install script which runs npm install, creates an .env through an interactive prompt and launches the project. This will make it very convenient for new users to setup and run the project.  

Or

Create a doc page with install instructions. Currently it isn't very hard to setup the project so this may be enough for now. Something like:
Clone the project
Run the database script
Run the server script
Rename the .env.template to .env
Adjust the values in the .env
Run npm install 
Run npm run dev

**Comment by OscarLarm** [comment]
@annk15 

Sure I'll look into it!

![Alt text](https://media1.tenor.com/m/QeYIXP4sXrwAAAAC/wink-eeehh.gif)

**Comment by git-hub-oscar** [comment]
@annk15 

Sure I'll look into it!

<div class="tenor-gif-embed" data-postid="22549662" data-share-method="host" data-aspect-ratio="1.25" data-width="100%"><a href="https://tenor.com/view/wink-eeehh-smilewink-gif-22549662">Wink Eeehh GIF</a>from <a href="https://tenor.com/search/wink-gifs">Wink GIFs</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script>
